server:
  bind: :8080
  response_status: 200
  shutdown_timeout: 30s
metrics:
  bind: :8081
  path: /metrics
proxy:
  remote_url: http://localhost:5000
  request_timeout: 120s
  num_clients: 700
queue:
  enabled: true
  workers: 20
  handle_per_second: 30
  max_retries: 1000
db:
  connection_string: 'host=localhost port=5432 user=postgres password=postgres dbname=asyncproxy sslmode=disable'
  max_connections: 2
