server:
  bind: :8080
  response_status: 200
proxy:
  remote_url: http://localhost:5000
  num_clients: 500
  request_timeout: 120 # seconds
queue:
  enabled: true
  workers: 10
redis:
  key: asyncproxy_requests
  url: redis://localhost:6379/0
metrics:
  path: /metrics
