server:
  bind: :8080
  response_status: 200
  shutdown_timeout: 30 # seconds
proxy:
  remote_url: http://localhost:5000
  num_clients: 300
  request_timeout: 120 # seconds
queue:
  type: sqlite
  enabled: true
  workers: 150
db:
  leveldb:
    name: request_db/leveldb
  sqlite:
    name: request_db/sqlite
metrics:
  path: /metrics
