server:
  bind: :8080
  response_status: 200
  shutdown_timeout: 30 # seconds
proxy:
  remote_url: http://localhost:5000
  num_clients: 500
  request_timeout: 120 # seconds
queue:
  type: db
  enabled: true
  workers: 120
db:
  name: request_db
redis:
  pool_size: 10
  key: asyncproxy_requests
  url: redis://localhost:6379/0
metrics:
  path: /metrics
