server:
  bind: :8080
  response_status: 200
  shutdown_timeout: 30 # seconds
proxy:
  remote_url: http://localhost:5000
  num_clients: 300
  request_timeout: 120 # seconds
queue:
  enabled: true
  workers: 150
db:
  connection_string: 'host=localhost port=5432 user=postgres password=postgres dbname=asyncproxy sslmode=disable'
  max_connections: 10
metrics:
  path: /metrics
