version: 2

workflows:
  version: 2
  test_deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - deploy:
          context: ebay-mag-k8s-deploy
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
jobs:
  test:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - run:
          name: Test
          command: make test

  deploy:
    docker:
      - image: gcr.io/evilmartians-public/gcloud-helm:282.0.0
    environment:
      IMAGE_NAME: gcr.io/ebay-mag/asyncproxy
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
          docker_layer_caching: true
      - run:
          name: Add make
          command: apk add --no-cache make
      - run:
          name: Build container
          command: make docker-build
      - run:
          name: Setup Google Cloud SDK
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_CLOUD_PROJECT_ID}
            gcloud --quiet auth configure-docker
      - run:
          name: Deploy container
          command: make docker-push
